# pyproject.toml

[build-system]
requires      = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "idrive_toolkit"
version = "1.0.1"
description = "Python toolkit for the iDrive project"
readme = "README.md"

authors = [{ name = "Pamparampampam" }]
license = { file = "LICENSE" }
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
]
keywords = ["iDrive", "discord", "fileStorage", "API", "sync", "transfer"]

dependencies = [
    "httpx ~= 0.28.1",
    "overrides ~= 7.7.0",
    "cryptography ~= 45.0.6",
    "packaging ~= 25.0",
    "requests",
    "websockets",
]
requires-python = ">=3.10"

[project.optional-dependencies]
transfer = [
    "pillow",
    "rawpy",
    "tqdm ~= 4.67.1",
]
gui = [
    "pillow",
    "tkinterdnd2",
]
all = [
    "pillow",
    "rawpy",
    "tkinterdnd2",
    "tqdm ~= 4.67.1",
]

[project.urls]
Github = "https://github.com/pam-param-pam/iDrive-toolkit"

[project.scripts]
idrive-gui = "idrive_toolkit.gui.BrowserGui:main"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
include = ["idrive_toolkit*"]

[tool.setuptools.package-data]
"idrive_toolkit.gui" = ["app_icon.ico", "app_icon.png"]

[tool.setuptools.exclude-package-data]
"*" = ["__pycache__/*", "*.py[cod]"]
